Fix error on editing content rules.
viewlet.render() was None, so: File "/plone/buildout-cache/eggs/plone.app.viewletmanager-2.0.9-py2.7.egg/plone/app/viewletmanager/manager.py", line 120, in render
   return u"\n".join(html)
TypeError: sequence item 1: expected string or Unicode, NoneType found